//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class CLIENTS: IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTS()
        {
            this.QUOTES = new HashSet<QUOTES>();
            this.PROJECTS = new HashSet<PROJECTS>();
        }
    
        public int CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_SHORT_NAME { get; set; }
        public short CLIENT_TYPE_ID { get; set; }
        public short CLIENT_STATUS_ID { get; set; }
        public string CLIENT_PHONE { get; set; }
        public string CLIENT_URL { get; set; }
        public string CLIENT_LINKEDIN { get; set; }
        public string CLIENT_CODE { get; set; }
        public int CLIENT_COUNTRY { get; set; }
        public int CLIENT_STATE { get; set; }
        public int CLIENT_CITY { get; set; }
        public string CLIENT_ADDRESS { get; set; }
        public Nullable<System.DateTime> CLIENT_SINCE { get; set; }
        public string POSTAL_CODE { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public bool IS_CANCELED { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public int COMPANY_ID { get; set; }
    
        public virtual CITIES CITIES { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual COMPANY_TYPES COMPANY_TYPES { get; set; }
        public virtual COUNTRIES COUNTRIES { get; set; }
        public virtual STATES STATES { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTES> QUOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTS> PROJECTS { get; set; }
    }
}
