//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class DEF_PROJECT_PHASES: IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEF_PROJECT_PHASES()
        {
            this.DEF_TASKS = new HashSet<DEF_TASKS>();
            this.PROJECT_PHASES = new HashSet<PROJECT_PHASES>();
        }
    
        public int PHASE_ID { get; set; }
        public string PHASE_NAME { get; set; }
        public int PROJECT_TYPE_ID { get; set; }
        public short PHASE_ORDER { get; set; }
        public string PHASE_DESC { get; set; }
        public string PHASE_COLOR { get; set; }
        public string WIDGET_COLOR { get; set; }
        public Nullable<short> CORRESPONDANT_STATUS { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        public virtual PROJECT_TYPES PROJECT_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEF_TASKS> DEF_TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_PHASES> PROJECT_PHASES { get; set; }
    }
}
