//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class DOCUMENTS: IEntity
    {
        public int DOC_ID { get; set; }
        public int UNIQ_ID { get; set; }
        public short DOCUMENT_TYPE_ID { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_PATH { get; set; }
        public string DOC_DESC { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public Nullable<int> PHASE_ID { get; set; }
        public Nullable<int> NOTE_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
        public Nullable<int> DOC_KIND { get; set; }
    
        public virtual DOCUMENT_TYPES DOCUMENT_TYPES { get; set; }
        public virtual QUOTES QUOTES { get; set; }
    }
}
