//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class EMPLOYEES: IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEES()
        {
            this.VEHICLES = new HashSet<VEHICLES>();
            this.SUPERVISOR_AREAS = new HashSet<SUPERVISOR_AREAS>();
            this.PROJECTS = new HashSet<PROJECTS>();
            this.PROJECTS1 = new HashSet<PROJECTS>();
            this.PROJECT_MEMBERS = new HashSet<PROJECT_MEMBERS>();
            this.PROJECT_MEMBERS1 = new HashSet<PROJECT_MEMBERS>();
            this.PROJECT_PHASES = new HashSet<PROJECT_PHASES>();
        }
    
        public int EMP_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMP_INITIALS { get; set; }
        public string EMP_NUMBER { get; set; }
        public string EMP_PHONE { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string PHONE_EXTENSION { get; set; }
        public int ROLE_ID { get; set; }
        public short EMP_STATUS_ID { get; set; }
        public Nullable<short> TITLE_ID { get; set; }
        public short DEPARTMENT_ID { get; set; }
        public Nullable<int> TEAM_LEADER_ID { get; set; }
        public short CONTRACT_TYPE_ID { get; set; }
        public string SYSTEM_USERNAME { get; set; }
        public string SYSTEM_PASSWORD { get; set; }
        public string EMAIL_USERNAME { get; set; }
        public string EMAIL_PASSWORD { get; set; }
        public Nullable<System.DateTime> HIRED_DATE { get; set; }
        public byte[] EMP_IMG { get; set; }
        public bool SHOW_SIGNATURE { get; set; }
        public string SIGNATURE { get; set; }
        public bool IS_LOCKED { get; set; }
        public string SECURITY_STAMP { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public bool IS_CANCELED { get; set; }
        public int COMPANY_ID { get; set; }
        public bool IS_SUPERVISOR { get; set; }
        public bool IS_DRIVER { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public bool IS_INSTALLER { get; set; }
        public string NAVBAR_CLASS { get; set; }
    
        public virtual CONTRACT_TYPES CONTRACT_TYPES { get; set; }
        public virtual DEPARTMENTS DEPARTMENTS { get; set; }
        public virtual TITLES TITLES { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLES> VEHICLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPERVISOR_AREAS> SUPERVISOR_AREAS { get; set; }
        public virtual ROLES ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTS> PROJECTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTS> PROJECTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_MEMBERS> PROJECT_MEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_MEMBERS> PROJECT_MEMBERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_PHASES> PROJECT_PHASES { get; set; }
    }
}
