//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JOB_MANAGER_DBEntities : DbContext
    {
        public JOB_MANAGER_DBEntities()
            : base("name=JOB_MANAGER_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTRACT_TYPES> CONTRACT_TYPES { get; set; }
        public virtual DbSet<DEPARTMENTS> DEPARTMENTS { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<TITLES> TITLES { get; set; }
        public virtual DbSet<COUNTRIES> COUNTRIES { get; set; }
        public virtual DbSet<STATES> STATES { get; set; }
        public virtual DbSet<CITIES> CITIES { get; set; }
        public virtual DbSet<STREET> STREET { get; set; }
        public virtual DbSet<PARAMETERS> PARAMETERS { get; set; }
        public virtual DbSet<COMPANY_TYPES> COMPANY_TYPES { get; set; }
        public virtual DbSet<COMPANY> COMPANY { get; set; }
        public virtual DbSet<VEHICLE_BODY_TYPES> VEHICLE_BODY_TYPES { get; set; }
        public virtual DbSet<VEHICLE_MAKES> VEHICLE_MAKES { get; set; }
        public virtual DbSet<VEHICLE_MODELS> VEHICLE_MODELS { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<VEHICLES> VEHICLES { get; set; }
        public virtual DbSet<SUPPLIERS> SUPPLIERS { get; set; }
        public virtual DbSet<SUPERVISOR_AREAS> SUPERVISOR_AREAS { get; set; }
        public virtual DbSet<ROLE_MENU> ROLE_MENU { get; set; }
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<CONTACTS> CONTACTS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<FLOOR_TYPES> FLOOR_TYPES { get; set; }
        public virtual DbSet<MATERIALS> MATERIALS { get; set; }
        public virtual DbSet<PROJECT_TYPES> PROJECT_TYPES { get; set; }
        public virtual DbSet<QUOTES> QUOTES { get; set; }
        public virtual DbSet<NOTE_TYPES> NOTE_TYPES { get; set; }
        public virtual DbSet<NOTES> NOTES { get; set; }
        public virtual DbSet<DOCUMENT_TYPES> DOCUMENT_TYPES { get; set; }
        public virtual DbSet<DOCUMENTS> DOCUMENTS { get; set; }
        public virtual DbSet<PROJECTS> PROJECTS { get; set; }
        public virtual DbSet<DEF_PROJECT_PHASES> DEF_PROJECT_PHASES { get; set; }
        public virtual DbSet<DEF_TASKS> DEF_TASKS { get; set; }
        public virtual DbSet<PROJECT_MEMBERS> PROJECT_MEMBERS { get; set; }
        public virtual DbSet<PROJECT_PHASES> PROJECT_PHASES { get; set; }
        public virtual DbSet<PROJECT_TASK> PROJECT_TASK { get; set; }
        public virtual DbSet<PROJECT_MEMBER_VIEW> PROJECT_MEMBER_VIEW { get; set; }
        public virtual DbSet<NOTE_VIEW> NOTE_VIEW { get; set; }
        public virtual DbSet<DOC_VIEW> DOC_VIEW { get; set; }
        public virtual DbSet<JOB_CALENDAR_VIEW> JOB_CALENDAR_VIEW { get; set; }
        public virtual DbSet<HOLIDAYS> HOLIDAYS { get; set; }
        public virtual DbSet<JOBSPHASESSUMMARY_VIEW> JOBSPHASESSUMMARY_VIEW { get; set; }
        public virtual DbSet<JOBSSUMMARY_VIEW> JOBSSUMMARY_VIEW { get; set; }
    }
}
