//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class JOBSPHASESSUMMARY_VIEW: IEntity
    {
        public int PROJECT_TYPE_ID { get; set; }
        public string PROJECT_TYPE_NAME { get; set; }
        public int PHASE_ID { get; set; }
        public string PHASE_NAME { get; set; }
        public int PHASE_ORDER { get; set; }
        public string WIDGET_COLOR { get; set; }
        public Nullable<int> COUNT { get; set; }
        public int COMPANY_ID { get; set; }
    }
}
