//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class NOTES: IEntity
    {
        public int NOTE_ID { get; set; }
        public int UNIQ_ID { get; set; }
        public short NOTE_KIND_ID { get; set; }
        public short NOTE_TYPE_ID { get; set; }
        public string NOTE_DESC { get; set; }
        public string NOTE_SUBJECT { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
        public Nullable<int> PHASE_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public Nullable<bool> SET_REMINDER { get; set; }
        public Nullable<System.DateTime> REMINDER_DATE { get; set; }
        public string ASSINGED_MEMBERS { get; set; }
        public string TO_REMINDER { get; set; }
    
        public virtual NOTE_TYPES NOTE_TYPES { get; set; }
        public virtual QUOTES QUOTES { get; set; }
    }
}
