//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class PROJECT_MEMBERS: IEntity
    {
        public int PROJECT_MEMBER_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public int PROJECT_ID { get; set; }
        public Nullable<int> PROJECT_PHASE_ID { get; set; }
        public Nullable<int> PROJECT_TASK_ID { get; set; }
        public Nullable<int> SUPERVISOR_ID { get; set; }
        public bool IS_SUPERVISOR { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual EMPLOYEES EMPLOYEES1 { get; set; }
        public virtual PROJECT_PHASES PROJECT_PHASES { get; set; }
        public virtual PROJECT_TASK PROJECT_TASK { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
    }
}
