//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class PROJECTS: IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECTS()
        {
            this.PROJECT_MEMBERS = new HashSet<PROJECT_MEMBERS>();
            this.PROJECT_PHASES = new HashSet<PROJECT_PHASES>();
            this.PROJECT_TASK = new HashSet<PROJECT_TASK>();
        }
    
        public int PROJECT_ID { get; set; }
        public string PROJECT_NUMBER { get; set; }
        public int CLIENT_ID { get; set; }
        public int PROJECT_TYPE_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public short PROJECT_STATUS { get; set; }
        public string ADR_LOT_NBR { get; set; }
        public string ADR_UNIT_NBR { get; set; }
        public string ADR_STREET_NBR { get; set; }
        public string ADR_STREET_NAME { get; set; }
        public string PROJECT_ADDRESS { get; set; }
        public int PROJECT_CITY { get; set; }
        public int PROJECT_STATE { get; set; }
        public int PROJECT_COUNTRY { get; set; }
        public string PROJECT_POSTAL_CODE { get; set; }
        public string CLIENT_PO_NBR { get; set; }
        public decimal PROJECT_AMOUNT { get; set; }
        public decimal PROJECT_ESTIMATED_VAL { get; set; }
        public decimal PROJECT_ACTUAL_VAL { get; set; }
        public int CABINETS_NBR { get; set; }
        public Nullable<int> CLIENT_SUPRVISOR { get; set; }
        public Nullable<int> PROJECT_SUPERVISOR { get; set; }
        public string PROJECT_DESC { get; set; }
        public Nullable<System.DateTime> INSTALLATION_DATE { get; set; }
        public System.DateTime PROJECT_START_DATE { get; set; }
        public Nullable<System.DateTime> PROJECT_END_DATE { get; set; }
        public int PROJECT_PROGRESS { get; set; }
        public int COMPANY_ID { get; set; }
        public bool USE_AS_TEMPLATE { get; set; }
        public string TEMPLATE_NAME { get; set; }
        public bool DISPLAY { get; set; }
        public short FLOOR_TYPE { get; set; }
        public int MATERIAL_ID { get; set; }
        public Nullable<short> STREET_SUFFIX_ID { get; set; }
        public Nullable<int> QUOTE_ID { get; set; }
        public bool IS_CANCELED { get; set; }
        public int EVENT_SIZE { get; set; }
        public Nullable<int> INSTALLER_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
    
        public virtual CITIES CITIES { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual CONTACTS CONTACTS { get; set; }
        public virtual COUNTRIES COUNTRIES { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual EMPLOYEES EMPLOYEES1 { get; set; }
        public virtual FLOOR_TYPES FLOOR_TYPES { get; set; }
        public virtual MATERIALS MATERIALS { get; set; }
        public virtual PROJECT_TYPES PROJECT_TYPES { get; set; }
        public virtual QUOTES QUOTES { get; set; }
        public virtual STATES STATES { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual STREET STREET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_MEMBERS> PROJECT_MEMBERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_PHASES> PROJECT_PHASES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_TASK> PROJECT_TASK { get; set; }
    }
}
