//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.Models
{
    using System;
    using System.Collections.Generic;
    using static JOB_MANAGER.Models.Abstact.Entity;

    public partial class SUPPLIERS: IEntity
    {
        public int SUPPLIER_ID { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SUPPLIER_NUMBER { get; set; }
        public short SUPPLIER_STATUS_ID { get; set; }
        public string SUPPLIER_PHONE { get; set; }
        public string SUPPLIER_EMAIL { get; set; }
        public string SUPPLIER_URL { get; set; }
        public int SUPPLIER_COUNTRY { get; set; }
        public int SUPPLIER_STATE { get; set; }
        public int SUPPLIER_CITY { get; set; }
        public string SUPPLIER_ADDRESS { get; set; }
        public string POSTAL_CODE { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
        public int COMPANY_ID { get; set; }
    
        public virtual CITIES CITIES { get; set; }
        public virtual COUNTRIES COUNTRIES { get; set; }
        public virtual STATES STATES { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
