//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.DATAACESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_CALENDAR_VIEW
    {
        public int PROJECT_ID { get; set; }
        public string TITLE { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string COLOR { get; set; }
        public string CONTENT { get; set; }
        public short STATUS_ID { get; set; }
    }
}
