//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.DATAACESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBSSUMMARY_VIEW
    {
        public int PROJECT_TYPE_ID { get; set; }
        public string PROJECT_TYPE_NAME { get; set; }
        public int COMPANY_ID { get; set; }
        public Nullable<int> COUNT { get; set; }
    }
}
