//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.DATAACESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETERS
    {
        public int IDENTID { get; set; }
        public string PARAM_NAME { get; set; }
        public string PARAM_STR { get; set; }
        public Nullable<int> PARAM_INT { get; set; }
        public Nullable<System.DateTime> PARAM_DT { get; set; }
        public byte[] PARAM_IMG { get; set; }
        public int COMPANY_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
    }
}
