//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.DATAACESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_PHASES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT_PHASES()
        {
            this.PROJECT_MEMBERS = new HashSet<PROJECT_MEMBERS>();
            this.PROJECT_TASK = new HashSet<PROJECT_TASK>();
        }
    
        public int PROJECT_PHASE_ID { get; set; }
        public int PROJECT_ID { get; set; }
        public int PHASE_ID { get; set; }
        public int PHASE_ORDER { get; set; }
        public Nullable<int> SUPERVISOR_ID { get; set; }
        public short PROJECT_PHASE_STATUS { get; set; }
        public int PROJECT_PHASE_PROGRESS { get; set; }
        public Nullable<System.DateTime> PHASE_START_DATE { get; set; }
        public Nullable<System.DateTime> PHASE_END_DATE { get; set; }
        public string PROJECT_PHASE_DESC { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
    
        public virtual DEF_PROJECT_PHASES DEF_PROJECT_PHASES { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_MEMBERS> PROJECT_MEMBERS { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_TASK> PROJECT_TASK { get; set; }
    }
}
