//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.DATAACESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT_TASK()
        {
            this.PROJECT_MEMBERS = new HashSet<PROJECT_MEMBERS>();
        }
    
        public int PROJECT_TASK_ID { get; set; }
        public int PROJECT_ID { get; set; }
        public int PROJECT_PHASE_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public short TASK_ORDER { get; set; }
        public string PROJECT_TASK_NAME { get; set; }
        public short PROJECT_TASK_STATUS { get; set; }
        public int PROJECT_TASK_PROGRESS { get; set; }
        public Nullable<System.DateTime> TASK_START_DATE { get; set; }
        public Nullable<System.DateTime> TASK_END_DATE { get; set; }
        public string PROJECT_TASK_DESC { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
    
        public virtual DEF_TASKS DEF_TASKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_MEMBERS> PROJECT_MEMBERS { get; set; }
        public virtual PROJECT_PHASES PROJECT_PHASES { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
