//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_MANAGER.DATAACESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUOTES()
        {
            this.NOTES = new HashSet<NOTES>();
            this.DOCUMENTS = new HashSet<DOCUMENTS>();
            this.PROJECTS = new HashSet<PROJECTS>();
        }
    
        public int QUOTE_ID { get; set; }
        public string QUOTE_NUMBER { get; set; }
        public int CLIENT_ID { get; set; }
        public int PROJECT_TYPE_ID { get; set; }
        public string QUOTE_NAME { get; set; }
        public short QUOTE_STATUS { get; set; }
        public string ADR_LOT_NBR { get; set; }
        public string ADR_UNIT_NBR { get; set; }
        public string ADR_STREET_NBR { get; set; }
        public string ADR_STREET_NAME { get; set; }
        public string QUOTE_ADDRESS { get; set; }
        public int QUOTE_CITY { get; set; }
        public int QUOTE_STATE { get; set; }
        public int QUOTE_COUNTRY { get; set; }
        public string QUOTE_POSTAL_CODE { get; set; }
        public decimal QUOTE_AMOUNT { get; set; }
        public int CABINETS_NBR { get; set; }
        public string QUOTE_DESC { get; set; }
        public System.DateTime QUOTE_START_DATE { get; set; }
        public Nullable<System.DateTime> QUOTE_EXPIRY_DATE { get; set; }
        public bool DISPLAY { get; set; }
        public short FLOOR_TYPE { get; set; }
        public int MATERIAL_ID { get; set; }
        public Nullable<short> STREET_SUFFIX_ID { get; set; }
        public string CONTACT_DESC { get; set; }
        public bool USE_AS_TEMPLATE { get; set; }
        public string TEMPLATE_NAME { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public int UPDATED_BY { get; set; }
        public bool IS_CANCELED { get; set; }
        public int COMPANY_ID { get; set; }
    
        public virtual CITIES CITIES { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual COUNTRIES COUNTRIES { get; set; }
        public virtual FLOOR_TYPES FLOOR_TYPES { get; set; }
        public virtual MATERIALS MATERIALS { get; set; }
        public virtual PROJECT_TYPES PROJECT_TYPES { get; set; }
        public virtual STATES STATES { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTES> NOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTS> DOCUMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTS> PROJECTS { get; set; }
    }
}
